PROGRAM Bai_toan_Bthop_voi_kthuoc_lon ;
Const   Max                   = 32000 ;
        Fi                    = 'activity.inp' ;
        Fo                    = 'activity.out' ;

Type    ArrL                  = Array [0..max] of Integer ;
        ArrS                  = Array [0..max] of Byte ;

Var     L ,tr ,csa            : ^ArrL ;
        MaxT                  : ArrL ;
        N                     : Longint ;

BEGIN
END .
 MaxT = max{maxT[i-1],maxT[L]+1}
 cs   32000*3
 MaxT 32000*3
 L    32000*2
{tr}
 Cac truong hop ma MaxT[i] = MaxT[i-1]
   - Khong co Li
   - MaxT[L[i]]+1 < MaxT[i]
